-- Run this in the Supabase SQL editor after creating your project.
-- Enable UUID extension (already enabled by default on Supabase)
create extension if not exists "pgcrypto";

-- ─── PROFILES ────────────────────────────────────────────────────────────────
-- Mirrors auth.users; created automatically via trigger on signup.
create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  email        text not null,
  first_name   text,
  last_name    text,
  created_at   timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─── INTAKE SUBMISSIONS ───────────────────────────────────────────────────────
-- Raw intake form data stored as JSONB.
create table public.intake_submissions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  data       jsonb not null,
  created_at timestamptz default now()
);

alter table public.intake_submissions enable row level security;

create policy "Users can read own intake"
  on public.intake_submissions for select
  using (auth.uid() = user_id);

-- ─── SNAPSHOTS ───────────────────────────────────────────────────────────────
-- Lightweight AI output generated immediately after intake (before payment).
create table public.snapshots (
  id                   uuid primary key default gen_random_uuid(),
  user_id              uuid not null references public.profiles(id) on delete cascade,
  split_recommendation text,
  calorie_target       int,
  protein_target       int,
  goal_timeline        text,
  coach_summary        text,
  created_at           timestamptz default now()
);

alter table public.snapshots enable row level security;

create policy "Users can read own snapshot"
  on public.snapshots for select
  using (auth.uid() = user_id);

-- ─── PLANS ───────────────────────────────────────────────────────────────────
-- Full 12-week plan returned by Anthropic, stored as JSONB.
create table public.plans (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles(id) on delete cascade,
  plan_data    jsonb not null,
  generated_at timestamptz default now()
);

alter table public.plans enable row level security;

create policy "Users can read own plan"
  on public.plans for select
  using (auth.uid() = user_id);

-- ─── SUBSCRIPTIONS ───────────────────────────────────────────────────────────
-- Mirrors Stripe subscription state. Updated by webhook on every event.
create table public.subscriptions (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null references public.profiles(id) on delete cascade,
  stripe_customer_id    text unique,
  stripe_subscription_id text unique,
  stripe_price_id       text,
  status                text not null default 'inactive',
  -- status values: inactive | active | past_due | canceled | trialing
  current_period_end    timestamptz,
  created_at            timestamptz default now(),
  updated_at            timestamptz default now()
);

alter table public.subscriptions enable row level security;

create policy "Users can read own subscription"
  on public.subscriptions for select
  using (auth.uid() = user_id);

-- Helper: is user's subscription active?
create or replace function public.is_subscribed(user_uuid uuid)
returns boolean language sql security definer as $$
  select exists (
    select 1 from public.subscriptions
    where user_id = user_uuid
      and status = 'active'
      and (current_period_end is null or current_period_end > now())
  );
$$;

-- ─── EXERCISE VIDEOS ─────────────────────────────────────────────────────────
-- Maps exercise library keys (snake_case IDs generated by AI, e.g. "barbell_squat")
-- to YouTube video IDs. One row per exercise; rows are added as footage is filmed.
-- No user_id — videos are global across all plans.
create table public.exercise_videos (
  exercise_key  text        primary key,  -- matches plan.exercise_library key
  youtube_id    text        not null,
  created_at    timestamptz default now()
);

alter table public.exercise_videos enable row level security;

-- Videos are not sensitive — any authenticated user may read them.
create policy "Authenticated users can read exercise videos"
  on public.exercise_videos for select
  to authenticated
  using (true);
